#!/bin/bash
#######################################
# FZF to ssh/sftp logins
# Step 1. Choose connection type
# Step 2. Choose connection
# STEP 4. CONNECT
#######################################

SSH_PATH=$HOME/.ssh
CUSTOM_PATHS=$SSH_PATH/init_login_paths
CREDENTIALS_FILE=$SSH_PATH/autologins

#######################################
# 1. CHOOSE TYPE_CONNECTION
#######################################
TYPE_CONNECTION_OPTIONS="ssh\nsftp"
TYPE_CONNECTION=$(echo -e $TYPE_CONNECTION_OPTIONS | fzf --prompt 'Type> ')

#######################################
# 2. CHOOSE CONNECTION
#######################################
SELECTION=$(cat $HOME/.ssh/init_login_paths | sort --reverse | fzf --prompt='Connection> ')
CONNECTION=$(echo $SELECTION | sed 's/ //g' |  awk -F\| '{print $1}')
INIT_LOCAL_PATH=$(echo $SELECTION | sed 's/ //g' |  awk -F\| '{print $2}')
INIT_REMOTE_PATH=$(echo $SELECTION | sed 's/ //g' | awk -F\| '{print $3}')

###########################
# 3. CONNECT
###########################
PUBLIC_KEY=YES
PASSWORD=

# Check if it has public key
if [ $(grep -w $CONNECTION $CREDENTIALS_FILE | wc -l) -eq 1 ]; then
    PUBLIC_KEY=NO
    PASSWORD=$(grep $CONNECTION $CREDENTIALS_FILE | awk '{print $3}')
fi

if [ $PUBLIC_KEY == NO ]; then
    if [ $INIT_LOCAL_PATH == default ]; then
        clear
        if [ $TYPE_CONNECTION == sftp ]; then
            sshpass -p $PASSWORD $TYPE_CONNECTION -t $CONNECTION
        else
            sshpass -p $PASSWORD $TYPE_CONNECTION -t ${CONNECTION} "pwd && exec \$SHELL"
        fi
    else
        cd $INIT_LOCAL_PATH
        clear
        if [ $TYPE_CONNECTION == sftp ]; then
            sshpass -p $PASSWORD $TYPE_CONNECTION ${CONNECTION}:${INIT_REMOTE_PATH}
        else
            sshpass -p $PASSWORD $TYPE_CONNECTION -t ${CONNECTION} "cd ${INIT_REMOTE_PATH} && pwd && exec \$SHELL"
        fi
    fi
    exit
fi

if [ $PUBLIC_KEY == YES ]; then
    if [ $INIT_LOCAL_PATH == default ]; then
        clear
        if [ $TYPE_CONNECTION == sftp ]; then
            $TYPE_CONNECTION ${CONNECTION}
        else
            $TYPE_CONNECTION -t ${CONNECTION} "pwd && exec \$SHELL"
        fi
    else
        cd $INIT_LOCAL_PATH
        clear
        if [ $TYPE_CONNECTION == sftp ]; then
            $TYPE_CONNECTION ${CONNECTION}:${INIT_REMOTE_PATH}
        else
            $TYPE_CONNECTION -t ${CONNECTION} "cd ${INIT_REMOTE_PATH} && pwd && exec \$SHELL"
        fi
    fi
fi
